server:
  port: 8080

spring:
  application:
    name: sc-gateway-server
  cloud:
    gateway:
      discovery:
        locator:
          enabled: false
          lowerCaseServiceId: true
      routes:
        - id: service-hi
          uri: lb://SERVICE-HI
          predicates:
            - Path=/demo/**
          filters:
            - StripPrefix=1


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/


#spring:
#  cloud:
#    gateway:
#      routes:
#        - id: limit_route
#          uri: http://httpbin.org:80/get
#          predicates:
#            - After=2017-01-20T17:42:47.789-07:00[America/Denver]
#          filters:
#            - name: RequestRateLimiter
#              args:
#                key-resolver: '#{@hostAddrKeyResolver}'
#                redis-rate-limiter.replenishRate: 1
#                redis-rate-limiter.burstCapacity: 3
#  application:
#    name: gateway-limiter
#  redis:
#    host: localhost
#    port: 6379
#    database: 0



#spring:
#  profiles:
#    active: request_time_route
#---
#spring:
#  cloud:
#    gateway:
#      routes:
#        - id: request_time_route
#          uri: http://httpbin.org:80/get
#          predicates:
#            - After=2017-01-20T17:42:47.789-07:00[America/Denver]
#          filters:
#            - RequestTime=false
#  profiles: request_time_route
#
#
#---
#spring:
#  cloud:
#    gateway:
#      routes:
#        - id: rewritepath_route
#          uri: https://blog.csdn.net
#          predicates:
#            - Path=/foo/**
#          filters:
#            - RewritePath=/foo/(?<segment>.*), /$\{segment}
#  profiles: rewritepath_route
#
#---
#spring:
#  cloud:
#    gateway:
#      routes:
#        - id: add_request_header_route
#          uri: http://httpbin.org:80/get
#          filters:
#            - AddRequestHeader=X-Request-Foo, Bar
#          predicates:
#            - After=2017-01-20T17:42:47.789-07:00[America/Denver]
#  profiles: add_request_header_route
#---
#spring:
#  cloud:
#    gateway:
#      routes:
#        - id: query_route
#          uri: http://httpbin.org:80/get
#          predicates:
#            - Query=foo, ba.
#  profiles: query_route
#---
#spring:
#  cloud:
#    gateway:
#      routes:
#        - id: path_route
#          uri: http://httpbin.org:80/get
#          predicates:
#            - Path=/foo/{segment}
#  profiles: path_route
#
#---
#spring:
#  cloud:
#    gateway:
#      routes:
#        - id: method_route
#          uri: http://httpbin.org:80/get
#          predicates:
#            - Method=get
#  profiles: method_route
#
#---
#spring:
#  cloud:
#    gateway:
#      routes:
#        - id: host_route
#          uri: http://httpbin.org:80/get
#          predicates:
#            - Host=**.rxx.com
#  profiles: host_route
#
#
#---
#spring:
#  cloud:
#    gateway:
#      routes:
#        - id: cookie_route
#          uri: http://httpbin.org:80/get
#          predicates:
#            - Cookie=name, rxx
#  profiles: cookie_route
#
#
#---
#spring:
#  cloud:
#    gateway:
#      routes:
#        - id: header_route
#          uri: http://httpbin.org:80/get
#          predicates:
#            - Header=X-Request-Id, \d+
#  profiles: header_route
#
#---
#spring:
#  cloud:
#    gateway:
#      routes:
#        - id: after_route
#          uri: http://httpbin.org:80/get
#          predicates:
#            - After=2017-01-20T17:42:47.789-07:00[America/Denver]
#  profiles: after_route
