server:
  port: 8900

spring:
  application:
    name: hello-web

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    lease-renewal-interval-in-seconds: 20
    lease-expiration-duration-in-seconds: 10
